disabled_rules:
- leading_whitespace
- trailing_whitespace
- large_tuple

excluded:
- FineDust/Supporting Files/AppDelegate.swift
- FineDust/Supporting Files/GeoConverter.swift
- FineDustTests/
- FineDust/SWXMLHash
- Pods/

line_length:
  warning: 99
  error: 120

identifier_name:
  excluded:
    - x
    - y
    - dx
